### ISSUE TITLE
마이페이지 구현

### ISSUE THREAD

**Issue by dani1552** [SWYP-Playground/Playground-Front#25]
### 📄 Describe

마이페이지 UI 퍼블리싱

### ✅ Tasks

- [x] 내 정보 메인 페이지
- [x] 내가 모집한 모임 페이지
- [x] 최근 논 친구 페이지
- [x] 회원정보 수정 페이지
- [x] 탈퇴 팝업
- [x] 문의하기 구현
- [x] 프로필 조회 페이지 (사진 o / x)
- [x] 추가적인 디자인 수정사항 반영
